version: '3.8'

services:
  app:
    build: .
    container_name: BrewCard_Batch_Updater_app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
